### ISSUE TITLE
body macro issues

### ISSUE THREAD

**Issue by slyrus** [sirherrbatka/vellum#2]
1. We probably shouldn't default to having the column vars in the body macro be special. I gather there is a use case for this, but i haven't seen it yet.
2. Apparently there is a thread safety issue with the body macro. Not sure if that's using different instances of body or the same instance in multiple threads. Either way, this should probably be fixed.
3. Do we really want to call this "body"? What about something like "rows"? I'm OK with shadowing CL names but &body body is such a common idiom in macros that I'm reluctant to have such a prominent macro be named "body".

**Comment by sirherrbatka** [comment]
1. Agreed.
2. There is, and after thinking about it, I know how to properly handle it. You see, it boils down to the header and indexes of the columns. Indexes are cached in let above the lambda to skip hash table lookups (and generic function calls). However, this is kinda stupid, because vellum:body is used mostly in transform so instead of let over lambda i can simply turn it into lambda over lambda which would ensure that closure instance actually used in the transform is unique. The drawback of doing it this way is that It would force user to write (funcall (body (...) ...) (or something in that vein) when using cl-ds.alg:group-by or cl-ds.alg:on-each but I guess it is worth it.
3. I am bad at naming things. Better name is welcome. "Rows" does not work for me, "columns" or "bind-row" sound better.

**Comment by sirherrbatka** [comment]
Ok, so I implemented the new design of the body macro and renamed it into bind-row. The new macro can, technically, still be used in an unsafe manner but it is by far more difficult. Sadly, this complicated postmodern example in the readme significantly, but I am convinced that it is worth it (especially since I actually already have (vellum:copy-from :postmodern ...) in the integration module (which needs to be moved out of the vellum system)). As for the CL-DS, I plan to slightly redesign how the function is accepted and that would make changes I made at least slightly less annoying. 

I did not introduce bind-row*/bind-rowv or anything like that. Perhaps in the future, I will simply make lambda form that bind-row expands into return secondary value (or something like that). I don't know if this is a good idea yet, but when I started this project, I decided to favor multipurpose tools instead of specialized functions.

Anyway, thanks for bringing out this issue.

**Comment by slyrus** [comment]
The new macro seems to be working. You'll have to explain to me the remaining unsafe issue some other time but I'm closing this for now. Thanks!

**Comment by sirherrbatka** [comment]
@slyrus I can explain this right away. So now, you are supposed to occasionally call BIND-ROW-CLOSURE to extract inner function. All of the vellum functions handle this so when you are passing bind-row into them, it is a guarantee that they will work on the separate instance of the function closed over the column-name -> column-position mapping. However, when used outside of the vellum, you are forced to extract BIND-ROW-CLOSURE manually. This is a problem because then you can store it and occasionally pass it to a wrong function call.

I think that this is relatively easy to solve, though. I can simply change BIND-ROW to expand into form constructing funcallable object. Directly calling this object will result in a slow, unoptimized, but safe behavior while vellum functions will continue to use the fast route with BIND-ROW-CLOSURE. This will also remove the need for ugliness around postmodern example.
