### ISSUE TITLE
Loading with quicklisp fails with: Package CL-DS.FANCY does not exist.

### ISSUE THREAD

**Issue by bon** [sirherrbatka/vellum#21]
Using SBCL 2.1.7.17

Cloned this repo to `ql:*local-project-directories*`

Failed with: `Package CL-DS.FANCY does not exist.`

**Comment by sirherrbatka** [comment]
Update quicklisp packages. (ql:update-all-dists)

**Comment by bon** [comment]
Thanks for the quick reply. Unfortunately it still fails with the same error after quicklisp update.

**Comment by sirherrbatka** [comment]
Ok. Investigating...

**Comment by sirherrbatka** [comment]
I can't replicate this issue. Cl-DS.FANCY was added recentl(ish) and so I thought that lingering cl-ds version in your local quicklisp is a problem. Otherwise I have no idea what is wrong.

To mitgate this problem you can clone https://github.com/sirherrbatka/cl-data-structures.git into ```ql:*local-project-directories*``` as well. Restart sbcl and attempt to load vellum system (or run the mushrooms example).

**Comment by bon** [comment]
OK I have it working now. I deleted all the fasls for cl-data-structures and reloaded. Thanks for your help.

**Comment by sirherrbatka** [comment]
Happy to help.

Breanndán Ó Nualláin pisze:
> OK I have it working now. I deleted all the fasls for cl-data-structures and
> reloaded. Thanks for your help.
-- 
Marek Kochanowicz
